import Head from "next/head";
import Layout from "@/components/layout";
import UsersList from "@/components/sections/userList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Users List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
          <UsersList/>
      </Layout>
    </>
  );
}
